baseURL = "https://nomasters.io"
personalURL = "https://n.2p5.xyz/"
title = "nomasters"
# for smart copyright line, leave this blank and check [params.copyright]

theme = "minimus"

preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "nomasters is an blog documenting the exploration of living life on your own terms."
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = ""                    # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "uncopyright"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
hideEntryNavigation = ["page"]      # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["recent_posts"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "-"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "posts"
weight = -10
identifier = "posts"
url = "/posts"

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1
